// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuntosExtras.DAL;

namespace PuntosExtras.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200307011404_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("PuntosExtras.Entidades.Personas", b =>
                {
                    b.Property<int>("PersonasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonasId");

                    b.ToTable("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
